export const ACTION_SOCKET_COMMENT = {
  CREATE_COMMENT: 'CREATE_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  DELETE_MULTIPLE_COMMENT: 'DELETE_MULTIPLE_COMMENT',
  REPLY_COMMENT: 'REPLY_COMMENT'
}
