'use client'
import { Box, useTheme } from '@mui/material'
import Head from 'next/head'
import CustomTextField from 'src/components/text-field'

export default function Home() {
  const theme = useTheme()
  console.log(theme)

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Hello world!</h1>
      <Box sx={{margin: 6, width: '200px'}}>
        <CustomTextField id='outlined-basic' label='Outlined' />
      </Box>
    </>
  )
}
